import React from 'react'
import Head from 'next/head'

const About = () => {
  return (
    <>
    <div>
    <Head>
        <title>StyleOn.com - About Us</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    </div>
    <div className='h-screen'>About</div>
    </>
  )
}

export default About