/* eslint-disable @next/next/no-img-element */
import Head from "next/head";
import Benifits from "../components/Benifits";
import BestSeller from "../components/BestSeller";
import ShopByCategory from "../components/ShopByCategory";

import styles from "../styles/Home.module.css";
import BannerSlider from "./BannerSlider";

export default function Home() {
  return (
    <>
      <div className={styles.container}>
        <Head>
          <title>Style.com</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        {/* banner */}
        <BannerSlider/>

        {/* bestseller */}

        <BestSeller/>

        {/* shopbycategory */}

        <ShopByCategory/>
        {/* benifits */}
        <Benifits />




      </div>
    </>
  );
}
