/* eslint-disable @next/next/no-img-element */
import Head from "next/head";
import Benifits from "../components/Benifits";
import Offers from "../components/offers";
import BestSeller from "../components/Trending";
import ShopByCategory from "../components/ShopByCategory";
import styles from "../styles/Home.module.css";
import Trending from "../components/Trending";
import Carousel from "../components/Carousel";

export default function Home() {
  return (
    <>
      <div>
        <Head>
          <title>Style.com</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>


        {/* Carousel */}

        <Carousel />

        {/* trending */}

        <Trending />

       

        {/* ShopByCategory */}
        

        <ShopByCategory />


         {/* offers */}

         <Offers />
        {/* benifits */}

        {/* <Benifits /> */}




      </div>
    </>
  );
}
