/* eslint-disable react-hooks/exhaustive-deps */
/* eslint-disable react-hooks/rules-of-hooks */
/* eslint-disable @next/next/no-img-element */
import { React, useState, useEffect } from 'react'
import Head from 'next/head';
import { useRouter } from 'next/router';
import Link from 'next/link';
const products = [
  {
    id: 1,
    name: 'Basic Tee',
    href: '#',
    imageSrc: 'https://tailwindui.com/img/ecommerce-images/product-page-01-related-product-01.jpg',
    imageAlt: "Front of men's Basic Tee in black.",
    price: '$35',
    delivary: 'Deliverd on 21 june 2023'
  },
  // More products...
]




const orders = () => {
  const router = useRouter();
  const [orders, setOrders] = useState([]);

  useEffect(() => {
    const fetchOrders = async () => {
      let a = await fetch(`${process.env.NEXT_PUBLIC_HOST}/api/pretransaction`, {
        method: 'POST', // or 'PUT'
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({ token: JSON.parse(localStorage.getItem('myuser')).token }),
      })

      let res = await a.json();
      setOrders(res.orders)
    }

    if (!localStorage.getItem('myuser')) {
      router.push('/')

    } else {
      fetchOrders()

    }
  }, [])

  return (
    <>
    <div>
    <Head>
        <title>StyleOn.com - MyOrders</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    </div>
    <section className="bg-white min-h-screen">
      <div className="mx-auto max-w-2xl py-16 px-4 sm:py-24 sm:px-6 lg:max-w-7xl lg:px-8">
        <h2 className="mx-auto text-center text-4xl font-bold tracking-tight text-gray-900">Order History</h2>

        <div className="mt-6 grid grid-cols-1 gap-y-10 gap-x-6 sm:grid-cols-2 lg:grid-cols-4 xl:gap-x-8">
          {/* {order.map((item) => (
            <div key={item._id} className="group relative">
            <div className="min-h-80 aspect-w-1 aspect-h-1 w-full overflow-hidden rounded-md bg-gray-200 group-hover:opacity-75 lg:aspect-none lg:h-80">
            <img
            src={item.img}
            alt={product.imageAlt}
            className="h-full w-full object-cover object-center lg:h-full lg:w-full"
            />
            </div>
            <div className="mt-4 flex justify-between">
            <div>
                  <h3 className="text-sm text-gray-700">
                  <a href={product.href}>
                  <span aria-hidden="true" className="absolute inset-0" />
                  {item.name}
                  </a>
                  </h3>
                  <p className="mt-1 text-xl  font-bold">divivery status</p>
                  </div>
                  <p className="text-sm font-medium text-gray-900">{item.amount}</p>
                  <Link href={'/order?'+ item._id}>
                  <p className="text-sm font-medium text-gray-900">more Deatils</p>
                  </Link>
                  
                  </div>
                  </div>
                ))} */}
        </div>

        <div className="mt-6 grid grid-cols-1 gap-y-10 gap-x-6 sm:grid-cols-2 lg:grid-cols-4 xl:gap-x-8">
          {products.map((product) => (
            <div key={product.id} className="group relative">
              <div className="min-h-80 aspect-w-1 aspect-h-1 w-full overflow-hidden rounded-md bg-gray-200 group-hover:opacity-75 lg:aspect-none lg:h-80">
                <img
                  src={product.imageSrc}
                  alt={product.imageAlt}
                  className="h-full w-full object-cover object-center lg:h-full lg:w-full"
                  />
              </div>
              <div className="mt-4 flex justify-between">
                <div>
                  <h3 className="text-sm text-gray-700">
                    <a href={product.href}>
                      <span aria-hidden="true" className="absolute inset-0" />
                      {product.name}
                    </a>
                  </h3>
                  <p className="mt-1 text-xl  font-bold">{product.delivary}</p>
                </div>
                <p className="text-sm font-medium text-gray-900">{product.price}</p>
              </div>
            </div>
          ))}
        </div>


      </div>
    </section>
          </>
  )
}


export default orders